"""new fields in user model

Revision ID: 829563caa003
Revises: c92acc0da83d
Create Date: 2021-09-17 19:30:05.192905

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '829563caa003'
down_revision = 'c92acc0da83d'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('user', sa.Column('about_me', sa.String(length=140), nullable=True))
    op.add_column('user', sa.Column('last_seen', sa.DateTime(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('user', 'last_seen')
    op.drop_column('user', 'about_me')
    # ### end Alembic commands ###
